### ISSUE TITLE
use standard open source license?

### ISSUE THREAD

**Issue by boegel** [losalamos/Pavilion#1]
It's unclear to me under which OSS license this is being made available...

Is the bit in the README the only relevant part? Please consider adding `LICENSE` file (see also https://help.github.com/articles/open-source-licensing/).

Maybe take a look at http://choosealicense.com/?

**Comment by cadejager** [comment]
A license file was added in commit cf5a1fcbd4978188b26259ede18b73d4e2e45eb5.

**Comment by boegel** [comment]
:+1:
