### ISSUE TITLE
Multiple test_arg lists

### ISSUE THREAD

**Issue by cadejager** [losalamos/Pavilion#4]
For some tests it would be more flexible to have multiple lists to specify test args. We could then concatenate all combinations  of them together.

**Comment by BenCasses** [comment]
This was discussed earlier, I like a list of lists format:
test_args: [ [ alpha, bravo, charlie ], [ foo ], [ one, two ] ]
would expand to 6 separate instances (all permutations) with args=
"alpha foo one"
"bravo foo one"
"charlie foo one"
"alpha foo two"
"bravo foo two"
"charlie foo two"
which further suggests exclusion lists (of lists)... for when you don't want certain permutations

**Comment by cadejager** [comment]
I was thinking of a slightly more complicated method. However, I think that would be ideal. I just added this because it was asked for, seemed reasonable, and I did not want to forget about it. I will start working on it when I have time.

**Comment by cadejager** [comment]
For clarification for George the current implantation is as follows:
test_args: ["too hot", "too cold", "just right"]
This would expand to:
"too hot"
"too cold"
"just right"

I guess if you hit an array of arrays every array provides a list of permutations to mix. However if you hit an array of strings only one argument is taken for each permutation.

**Comment by gsparrow** [comment]
@BenCasses, I have created a git repository for the function I think will solve this problem. It is called [pavillion-term-expansion](https://github.com/gsparrow/pavillion-term-expansion) Please check it out, and test to see if it will meet your needs.

**Comment by cadejager** [comment]
Ben, we are working on integrating it now. Although it would not be unwelcome I do not expect any action from you.

**Comment by BenCasses** [comment]
Looks like argument order is not respected by this function.  See built in test 1.  I would expect it to expand to ['a x b c','a y b c',...].  Many apps impose an ordering over their arguments, for example [Presta allred](https://asc.llnl.gov/computing_resources/purple/archive/benchmarks/presta/) takes 3 ordered numerical arguments.

**Comment by cadejager** [comment]
I agree that that that should be a requirement. We will make sure that the function does that before it is integrated.

**Comment by cadejager** [comment]
This has been implemented fully in commit 01b0b27352a4cc432725bc5bfbcb93811b14026c
