### ISSUE TITLE
2.0 - Copy test build into working space

### ISSUE THREAD

**Issue by pflarr** [losalamos/Pavilion#46]
In old pavilion, this often copied the entire test source into the working space. In 2.0, we'll be building a directory structure that consists entirely of sim-links into the pre-built test. The bash way to do this would be to `cp -as` the build directory, but it's probably best to just do this in python.

**Comment by nicholas-sly** [comment]
I can't assign this to myself, but I'm looking at it now.  I'm going to just implement it as a function in its own file for now and reference that from the current pavilion files for testing.

The process I've sort of worked out for now is to assume that the working space directory has already been determined and to iterate over the source_location using os.scandir() to create the directory structure with symlinks to all files.

Does this seem reasonable?
