### ISSUE TITLE
Build Option in test yamls runs from directory test was launched from

### ISSUE THREAD

**Issue by cadejager** [losalamos/Pavilion#5]
If you set a build script in the options for build. The build script that is launched in the original test source directory. The working directory it is launched from is wherever "pav run_test_suite" is called from.

I think that the build script should be launched so that its working directory is the working space of the test. Another option would be to launch it in the original test directory but I think that by design pavilion tests should not modify the original source directory.

I also think that for consistency sake the build script that is called should be the one from the working directory.

**Comment by BenCasses** [comment]
Couldn't every test instance running its own build dramatically increase the size of working space?

If some instance needs a special build, you can easily do the clone/get, make, verify process in the run script for that instance.

I think build options were intended as something more global for a test.  If every instance of mytest runs "/src/mytest/make", the first instance goes through the pain of making, and later instances benefit from it.  I don't know what concurrent "make" commands might do, so I'm a little more cautious:

Currently I use a separate BUILD master yaml file.  It fans out to a single build yaml for each test that runs the build process and passes if it sees that the appropriate binaries were created.  I don't move on to running tests unless I get 100% out of BUILD.  For a few very special instances, I run the build as part of the test in working space.

**Comment by cadejager** [comment]
So I believe you BUILD stuff is connected to your wiring framework which we have not had time to look into but would like to look into. As of last week I have a student that I would like to look into moving us over to it but has another task we need done first. We do build 

However, we have one test that has an input deck which is C++ code. We don't want to compile on the compute nodes because they are not normal and there are too many combinations to compile everything ahead of time. I think that this functionality already exists with the build option but It usage seems to be non intuitive. I wanted to make sure that it was not being used before I changed it.

The changes I am proposing is that the build script dumps its output to a log (currently I think the output goes no where), runs out of the working space, and is given a working directory in the working space at launch.

**Comment by BenCasses** [comment]
I don't think these changes will hurt me.

**Comment by cadejager** [comment]
The following changes will be made to resolve this issue:
1. The build script will dump to the same log as the run script.
2. The build script will be launched with its working directory set to the work space of the test.
3. The build script launched will be the one in the work space
4. If build is set to true *.c and other source files will be copied unlike the default where they are ignored.

**Comment by cadejager** [comment]
This issue has been fixed by commit f3621df6318b2cde41937f1c50ba7763cb965a93
